services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: database-test
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my_network
    container_name: DATABASE
  app:
    image: ${IMAGE_NAME}
    container_name: applicationAPI
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database-test
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
        - my_network
  nginx:
    image: nginx:latest
    container_name: proxy
    restart: always
    depends_on:
       - app
    ports:
      - "80:80"
    volumes:
      - ./myapp/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./myapp/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
