name: Ansible EC2 Provision and Deployment

on:
  workflow_run:
    workflows: ["Docker Compose Image CI"]
    types: 
      - completed
jobs:
#install ansible -done
#log into github ansible repo with credentials -done with token
  #provide credentials for said repo - NEEDED - done
#checkout ansible script - done
#install docker cli? - preinstalled on runner 
#checkout docker-compose script -done
  provision-and-deploy-to-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Ansible install
        run: |
          sudo apt update
          sudo apt install -y ansible
      
      - name: Create folder for ansible repository
        run: mkdir ansible-script

      - name: Checkout ansible script
        uses: actions/checkout@v4
        with:
          repository: ${{secrets.REMOTE_REPO}} #add to git! - done
          ref: ${{secrets.REMOTE_REPO_BRANCH}} #add to git! - done 
          token: ${{secrets.REMOTE_GITHUB_TOKEN}} #modify to use a token for remote repo! - done
          path: ansible-script
#set up ec2 ssh key
  # -add secret for ssh key -done
  # -add secret for host!!! 
      - name: Set up SSH key
        run: |
          echo "${{secrets.EC2_SSH_KEY}}" > key.pem
          chmod 600 key.pem
           
#prepare inventory file with secrets

   #   - name: Set up env variables for inventory 
    #    run: |
     #     echo "EC2_HOST=${{secrets.EC2_HOST}}" >> $GITHUB_ENV
      #    echo "EC2_USER=${{secrets.EC2_USER}}" >> $GITHUB_ENV
     
      #- name: Update inventory file with env variables
       # run:
        #  envsubst < inventory.ini > inventory_final.ini


#run ansible script on remote node
            #don't forget to add EC2 host ip to secrets
      - name: Run ansible playbook on ec2 instance
        env:
          IMAGE_NAME: ${{secrets.IMAGE_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: |     
          cd ansible-script
          export ANSIBLE_HOST_KEY_CHECKING=False     
          ansible-playbook -i inventory.ini playbook.yaml 
          
#======================= THIS IS FOR LATER, SUBJECT TO CHANGE ===================
#log into ec2 node using root user? 
#create ansible user
  # -add secret for ansible user
#place ssh key from root user into ansible user


  

