name: Ansible EC2 Provision and Deployment

on:
  workflow_run:
    workflows: ["Docker Compose Image CI"]
    types: 
      - completed
jobs:

  provision-and-deploy-to-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Ansible install
        run: |
          sudo apt update
          sudo apt install -y ansible
      
      - name: Create folder for ansible repository
        run: mkdir ansible-script

      - name: Checkout ansible script
        uses: actions/checkout@v4
        with:
          repository: ${{secrets.REMOTE_REPO}} 
          ref: ${{secrets.REMOTE_REPO_BRANCH}}  
          token: ${{secrets.REMOTE_GITHUB_TOKEN}} 
          path: ansible-script

      - name: Set up SSH key
        run: |
          echo "${{secrets.EC2_SSH_KEY}}" > key.pem
          echo "${{secrets.PRIVATE_NODE_KEY}}" > key_private.pem
          chmod 600 key.pem key_private.pem
           
#prepare inventory file with secrets

   #   - name: Set up env variables for inventory 
    #    run: |
     #     echo "EC2_HOST=${{secrets.EC2_HOST}}" >> $GITHUB_ENV
      #    echo "EC2_USER=${{secrets.EC2_USER}}" >> $GITHUB_ENV
     
      #- name: Update inventory file with env variables
       # run:
        #  envsubst < inventory.ini > inventory_final.ini


      - name: Moving files prior to deployment into directory
        run: |
          mv key.pem ansible-script
          mv key_private.pem ansible-script 
          mv docker-compose.yml ansible-script
          mv nginx ansible-script
          
      - name: Run ansible playbook on ec2 instance
        env:
          IMAGE_NAME: ${{secrets.IMAGE_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: |     
          cd ansible-script
          export ANSIBLE_HOST_KEY_CHECKING=False     
          ansible-playbook -i inventory.ini playbook.yaml 
          