name: Docker Compose Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: code Checkout
      uses: actions/checkout@v4
      
    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build the Docker image
      run: docker compose build --tag ${{secrets.DOCKER_USERNAME}}/${{secrets.REPO_NAME}}:latest
    
    - name: Push the image to DockerHub registry
      run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.REPO_NAME}}:latest
